# Generated by Django 5.2 on 2025-04-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogModule', '0003_category_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/image/'),
        ),
    ]
