# Generated by Django 5.2 on 2025-04-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogModule', '0004_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='images',
            field=models.JSONField(default=list),
        ),
    ]
