# Generated by Django 5.2 on 2025-04-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogModule', '0006_alter_blog_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='images',
        ),
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
