# Generated by Django 5.2 on 2025-04-19 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OrderModule', '0001_initial'),
        ('ProductModule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='OrderModule.deliverydetail'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='OrderModule.discountcode'),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', to='ProductModule.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_gateway_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='OrderModule.paymentgatewayresponse'),
        ),
    ]
