# Generated by Django 5.2 on 2025-04-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderModule', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_details',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_gateway_response',
        ),
        migrations.DeleteModel(
            name='DeliveryDetail',
        ),
        migrations.DeleteModel(
            name='DiscountCode',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='PaymentGatewayResponse',
        ),
    ]
