# Generated by Django 5.2 on 2025-04-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderModule', '0003_alter_order_authority_alter_order_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
