# Generated by Django 5.2 on 2025-04-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketModul', '0003_message_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
