# Generated by Django 5.2 on 2025-04-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketModul', '0004_remove_message_customer_name_ticket_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='file_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
