# Generated by Django 5.2 on 2025-04-19 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.PositiveIntegerField()),
                ('product_type', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=255)),
                ('weight_capacity', models.PositiveIntegerField(help_text='Weight capacity in kg')),
                ('display', models.CharField(max_length=100)),
                ('motor_power', models.CharField(max_length=100)),
                ('product_weight', models.PositiveIntegerField(help_text='Weight in kg')),
                ('weight', models.CharField(max_length=100)),
                ('dimensions', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('warranty', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('sales', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('features', models.JSONField(default=list)),
                ('images', models.JSONField(default=list)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ProductModule.category')),
            ],
        ),
    ]
