# Generated by Django 5.2 on 2025-04-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='display',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='motor_power',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
