# Generated by Django 5.2 on 2025-04-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductModule', '0002_alter_product_display_alter_product_motor_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Weight capacity in kg', null=True),
        ),
    ]
